### ISSUE TITLE
Keras model error

### ISSUE THREAD

**Issue by mpariente** [aliutkus/speechmetrics#8]
When running `test.py`, I get the following error : 
```
Trying ABSOLUTE metrics: 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    metrics = sm.load('absolute', window)
  File "/home/mparient/code_perso/cloned/speechmetrics/speechmetrics/__init__.py", line 151, in load
    new_metric = load_function(window)
  File "/home/mparient/code_perso/cloned/speechmetrics/speechmetrics/absolute/mosnet/__init__.py", line 22, in load
    mosnet = MOSNet(window, hop)
  File "/home/mparient/code_perso/cloned/speechmetrics/speechmetrics/absolute/mosnet/model.py", line 36, in __init__
    padding='same'))(re_input)
  File "/home/mparient/.virtualenvs/speechmetrics/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 817, in __call__
    self._maybe_build(inputs)
  File "/home/mparient/.virtualenvs/speechmetrics/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "/home/mparient/.virtualenvs/speechmetrics/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 153, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```
Installing the b1 version (as specified in the original repo) doesn't solve the problem. Any idea?

**Comment by aliutkus** [comment]
hi, damn, no I have no clue, it was working at the time. Again some tensorflow problem... =(

Is it some special test file you're using ? or the default one embedded on the repo ?

**Comment by mpariente** [comment]
I didn't try the implementation from the official repo yet, just wanted to report this. 
This is with the examples/test.py from the repo

**Comment by aliutkus** [comment]
what about it ?

**Comment by mpariente** [comment]
Can you run the test file from the repo? 
I consistently got this error. 
I'm probably not going to use mosnet now so I don't really mind but I just wanted to let you know it might be broken.

**Comment by aliutkus** [comment]
Ok thanks I will try an environnent from scratch
